x=linspace(-2*pi, 2*pi, 100);
y=linspace(-2*pi, 2*pi, 100);
[X,Y] = meshgrid(x,y);
Z = sin(X).*cos(Y);
figure;
surf(X,Y,Z);
title('Plot of sin(x)cos(x)');
xlabel('x');
ylabel('y');
zlabel('f(x,y)');
